# Generated by Django 4.0.2 on 2022-06-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('data', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'plates',
                'managed': False,
            },
        ),
    ]
