# Generated by Django 4.0.2 on 2022-06-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ELISA_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plates',
            table='Plates',
        ),
    ]
