# Generated by Django 4.0.2 on 2022-06-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ELISA_core', '0002_alter_plates_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plates',
            table='plates',
        ),
    ]
